### ISSUE TITLE
Migrate Deployments methods over to ProcessInstances

### ISSUE THREAD

**Issue by jkranes** [smart-cow/scow#36]
Deployments were a holdover from the older JBPM 4.x object model and don't really make any sense in the JBPM 5.x world.  So, we should migrate all functionality currentiy under Deployments and move to equivalent function under /processInstances:  Once all clients have started using the new endpoints, the old Deployments endpoints can be removed.
- POST to /deployments/v2 becomes POST to /processInstances

**Comment by lewisloren** [comment]
Due Feb. 2

**Comment by brosenberg42** [comment]
@jkranes 
I'm kind of confused. I thought we would deprecate `/deployments`, in favor of `/processes`. 
I also don't know if we need both `/processDefinitions` and `/proccesses`.

**Comment by jkranes** [comment]
/processDefinitions is used to return a &lt;processDefinition&gt; object, which contains metadata about the process.  This is a holdover from JBPM 4.x and previously was more useful when we had multiple versions of each process, which we no longer keep.  So the only really useful thing here is that it provides a list of process IDs, which you can then use to get the details if you want from the /processes endpoint.

/processes is used to get the full process XML for a single process.  It probably also makes more sense to POST a new or updated process to the /processes endpoint. (as a replacement for /deployments)

**Comment by brosenberg42** [comment]
I refactored some of the api methods in the Processes, ProcessInstances, and Tasks controllers. The inputs are all the same, but for some methods the output has changed slightly. 

Most of the changes to the output were changes to the error codes that were returned. For most errors 500 (Internal Server Error) was returned. Where appropriate, more specific error codes are returned. 

A few of the methods in the tasks controller had their bodies commented out, and only returned empty lists or objects without an error code. I changed those methods to return 501 (Not implemented). This may cause problems for certain clients, because before it returned an successful respone code (2XX), but now it will return an error response code.
