### ISSUE TITLE
Check for running instances when making workflow updates

### ISSUE THREAD

**Issue by jkranes** [smart-cow/scow#45]
If a workflow is updated while instances are still running, this can lead to errors, for example when completing tasks for the workflow.  There is really no way to know strictly whether changes to the workflow will cause problems.  We can be strict and refuse to accept workflow changes if instances are running, or we could just provide a warning of some kind.  Or the webapp could check for running instances and give a warning, possibly with the option of aborting all running instances.

**Comment by lewisloren** [comment]
@brosenberg42 look into the migrate feature.

**Comment by jkranes** [comment]
I think this may be more complicated than I originally thought.  If I read the JBPM docs correctly, they seem to be assuming that the migration (using WorkflowProcessInstanceUpgrader) always involves a different process ID, not a replacement of a process with the same ID.  The docs seem to say that you should never replace a process with the same ID (which of course we do all the time).

See http://docs.jboss.org/jbpm/v5.4/userguide/ch.core-basics.html#d0e2318

**Comment by brosenberg42** [comment]
One approach I was thinking of was to change the way new processes are created to better match REST conventions. 

When you do a POST you are not supposed to give the server the id of the object, the server is supposed to assign the id. According the [HTTP RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.5) "If a resource has been created on the origin server, the response SHOULD be 201 (Created) and contain an entity which describes the status of the request and refers to the new resource, and a Location header (see section 14.30)."

The PUT method is used when you want to specify the id. In the PUT method we can deal with what to do when there are running instances. I'm thinking that if there are running instances, it should use status code 409 and list the running instances.
Status code 409's definition is:
The request could not be completed due to a conflict with the current state of the resource. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. 

The response body SHOULD include enough information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.

Conflicts are most likely to occur in response to a PUT request. For example, if versioning were being used and the entity being PUT included changes to a resource which conflict with those made by an earlier (third-party) request, the server might use the 409 response to indicate that it can't complete the request. In this case, the response entity would likely contain a list of the differences between the two versions in a format defined by the response Content-Type.

**Comment by brosenberg42** [comment]
I think that since we are talking about changing the endpoints in #36, we can resolve these two issues together.

**Comment by brosenberg42** [comment]
The pattern of using 409 (Conflict), where appropriate, has been added to other api methods.

**Comment by lewisloren** [comment]
Matt will add a warning message indicating that replacing a running instance will delete those running instances.

**Comment by brosenberg42** [comment]
DELETE `/proccesses/{workflowname}/processInstances` will remove all running instances of a workflow
